-- EXPORT A NFS

EXPORT "TESTBACKUP"."*" AS BINARY INTO '/tmp/exports/TESTBACKUP' WITH REPLACE threads 10;
EXPORT "TESTBACKUP"."*" AS BINARY INTO '/tmp/exports/TESTBACKUP' WITH REPLACE threads 5;
EXPORT "TESTBACKUP"."*" AS BINARY INTO '/tmp/exports/TESTBACKUP' WITH REPLACE threads 1;

-- EXPORT A FileSystem local a SUSE

EXPORT "TESTBACKUP"."*" AS BINARY INTO '/tmp/TESTBACKUP' WITH REPLACE threads 10;
EXPORT "TESTBACKUP"."*" AS BINARY INTO '/tmp/TESTBACKUP' WITH REPLACE threads 5;
EXPORT "TESTBACKUP"."*" AS BINARY INTO '/tmp/TESTBACKUP' WITH REPLACE threads 1;


--import "TESTBACKUP"."*" as binary from '/tmp/exports/TESTBACKUP' with ignore existing threads 10 rename schema "TESTBACKUP" to "TESTBACKUP2";
