select * from M_RECORD_LOCKS;
select LOCK_OWNER_APPLICATION,LOCK_OWNER_APPLICATION_USER,LOCK_OWNER_APPLICATION_SOURCE, * from _SYS_STATISTICS.HOST_BLOCKED_TRANSACTIONS order by SERVER_TIMESTAMP desc;
