--CREATE USER TEST01 PASSWORD Password01$;
--ALTER USER TEST01 PASSWORD Password02$ NO FORCE_FIRST_PASSWORD_CHANGE;
select * from users;

--ALTER USER TEST01 RESET CONNECT ATTEMPTS;
-- ALTER USER TEST01 ACTIVATE USER NOW; 
--https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/1.0.12/en-US/20d3459f75191014a7bbeb670bad8850.html
SELECT 
    USER_NAME, 
    USER_DEACTIVATED, 
    DEACTIVATION_TIME, 
    INVALID_CONNECT_ATTEMPTS, 
    VALID_UNTIL 
FROM "SYS"."USERS"  
WHERE USER_NAME='TEST01';

SELECT DISTINCT object_type, privilege, grantee
FROM SYS.GRANTED_PRIVILEGES
where privilege = 'USER ADMIN';
GRANT USER ADMIN TO TEST01; 

--Password Lifetime
ALTER USER <user_name> DISABLE PASSWORD LIFETIME
