/* Caso Freiberg Pedido 188 que no se puede cancelar */
/*OWTM y OWST es para configurar el workflow*/
select * from OWTM;
select * from OWST;

/* WddStatus debe ser - Without W Pending Y Approved  N Rejected  P Generated  A Generated by Authorizer C Canceled */
select "WddStatus", * from OPOR where "DocNum" in (400,188);
/* Dcoument Approval Header*/
/* Status puede ser W Pending Y Approved N Rejected P Generated A Generated by Authorizer C Canceled */
/* ProcesStat puede ser W Pending Y Approved N Rejected P Generated A Generated by Authorizer C Canceled */
/* Llama la atencion que el pedido 199 tiene dos entradas una en Y approved y otra en P generated */
select "Status", "ProcesStat", * from OWDD where "DocEntry" in (902,528) order by "DocDate" desc;
/* Dcoument Approval Autorizers*/
select * from WDD1 where "WddCode" in (76,53);
/* Dcoument Approval Terms*/
select * from WDD2;
select "WddStatus",* from ODRF where "DocEntry" in(1065, 634);
/*Diferencia en DocStatus uno esta C Closed 634 y otro O Opened 1065*/

/*Parche horrible */


--update OWDD SET "Status" = 'Y' , "ProcesStat" = 'P', "IsDraft" ='N'  where "DocEntry" = 528;
UPDATE OPOR set "WddStatus" = 'P' where "DocNum" in (188);




/* Repeticion del experimiento en SBODEMOAR2*/
/* Voy a trabajar con una orden de venta. Al ser sometida a una aprobacion NO se crea en ORDR sino en ODRF*/
/* EL DocNum (candidato) es 551, el DocEntry en ODRF es 44*/ 
/* Antes que alguien apruebe o desaprueba en OWDD el "Status", "ProcesStat" estan en W DocEntry esta en blanco y los campos IsDraft esta en Y DraftType 112 y DarftEntry 44 (observece que apunta al 44 de la ODRF)*/
/* Cuando lo autorizo, el DocEntry de OWDD sigue en blanco pero "Status", "ProcesStat" estan en Y */
/* Ahora le volvio al creador para que efectivamente la cree*/
/* Cuando le da crear efectivamente aparece en ORDR y el WddStatus en P */
select "WddStatus", * from SBODEMOAR2.ORDR where "DocNum" >= 551;
select "Status", "ProcesStat", * from SBODEMOAR2.OWDD
 --where "DocEntry" = 528 
 order by "DocDate" desc;

 /* Que pasa si le pido otro cambio? */
 /*El WddStatus de la ORDR y la OWDD vuelve a cambiar a W*/
 /*Cuando se le da autorizar en ORDR pasa a Y en OWDD pasa a  Y y P algo distinto.....Porque me falta ACTAULIZAR !!!!*/
